directories:
  output: dist_electron
  buildResources: assets
appId: com.yuanawl.yuanawl
productName: 元阿网络后台
nsis:
  oneClick: false
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  allowToChangeInstallationDirectory: true
  perMachine: true
  deleteAppDataOnUninstall: true
  installerIcon: public/icon.ico
  installerHeaderIcon: public/icon.ico
publish:
  provider: generic
  url: ''
  channel: latest
mac:
  category: public.app-category.utilities
files:
  - filter:
      - dist/**/*
      - src/**/*
electronVersion: 24.4.0
